### ISSUE TITLE
[Feature Request] Find Wrapper by Data Attribute

### ISSUE THREAD

**Issue by skoenfaelt** [vuejs/vue-test-utils#1861]
### Feature Description

Its not a best practice to find elements by css classes. A better and concise solution is the use of data attributes. So we can give those testable elements a `data-testId` with a specific name

eg.

`<input data-testId="passwordInput" />`

Now I can use this data attribute across my test frameworks (unit and e2e testing) without touching other unwanted elements.

### Problem

If I search an element by

```js
const firstTypeBasedTicketCard = wrapper.find(
      '[data-test="typeBasedTicketCard-support-request"]'
)

expect(firstTypeBasedTicketCard.exists()).toBe(true)
```

I get an error

```
Error: expect(received).toBe(expected) // Object.is equality

Expected: true
Received: false
```

So I can assume my element does not exist, which is wrong, since the e2e test with nightwatchJs finds the element.

### Expected behaviour

I expect to find an element via data attributes.

Edit: Here is my Component HTML

as you see I declared: 
```
:data-test="`typeBasedTicketCard-${ticketType.id}`"
```

```vue
<template>
  <div>
    <div class="ml-2 text-h5">{{ $t('common.createTicket') }}</div>
    <v-row class="mt-n2">
      <v-col
        v-for="ticketType in ticketTypes"
        :key="ticketType.id"
        cols="12"
        lg="4"
      >
        <v-hover v-slot="{ hover }">
          <v-card
            :elevation="hover ? 16 : 2"
            height="100%"
            nuxt
            exact
            :data-test="`typeBasedTicketCard-${ticketType.id}`"
            :to="
              localePath(
                `/dashboard/product/${productId}/ticket/wizard?type=${ticketType.id}`
              )
            "
          >
            <v-card-title>
              <h4>{{ $t(ticketType.title) }}</h4>
            </v-card-title>
            <v-card-text>
              {{ $t(ticketType.description) }}
            </v-card-text>
          </v-card>
        </v-hover>
      </v-col>
    </v-row>
  </div>
</template>
```

**Comment by afontcu** [comment]
Hi!

> Its not a best practice to find elements by css classes

Totally agree on that :) 

Since `wrapper.find` accepts any valid DOM selector, you can already write something like

```js
wrapper.find(`[data-test="typeBasedTicketCard-${ticketType.id}"]`)
```


Also, this is kind of solved in user-land by Testing Library (there's [a specific version for Vue](https://testing-library.com/docs/vue-testing-library/intro/), too). Testing Lib uses `data-testid`,  but it would serve your needs, too.

Hope it helps!

**Comment by skoenfaelt** [comment]
Thank you,

It seems it's a problem with rendering. You pointed out that data attributes are already functional, it's also in the docs. Then I ask myself, why I can find my data attributes.

I try the testing library and update this issue if I get anything to work. If no update comes, assume I still have that issue :D

**Comment by skoenfaelt** [comment]
Okay I close this issue, since i found the magic.

The problem is not about the data-*, its about the rendered HTML. I used the snapshot function to show the generated HTML


```
<div>
  <div class=\"ml-2 text-h5\">common.createTicket</div>
  <v-row class=\"mt-n2\">
    <v-col cols=\"12\" lg=\"4\">
      <v-hover></v-hover>
    </v-col>
    <v-col cols=\"12\" lg=\"4\">
      <v-hover></v-hover>
    </v-col>
    <v-col cols=\"12\" lg=\"4\">
      <v-hover></v-hover>
    </v-col>
  </v-row>
</div>
```

as you see, v-hover has no content, which is actually a problem. So I think the issue is about vuetify testing.

**Comment by skoenfaelt** [comment]
https://github.com/vuetifyjs/vuetify/discussions/13836
