### ISSUE TITLE
`isVisible()` is not a function

### ISSUE THREAD

**Issue by Prior99** [vuejs/vue-test-utils#436]
### Version
1.0.0-beta.11

### Reproduction link
[https://codesandbox.io/s/mo2r2y6j09](https://codesandbox.io/s/mo2r2y6j09)

### Steps to reproduce
Use the function `isVisible()` according to [the documentation](https://vue-test-utils.vuejs.org/en/api/wrapper/isVisible.html).

### What is expected?
The test utilities check whether an element in the wrapper is visible.

### What is actually happening?
A `TypeError` occurs:

```
TypeError: el.find(...).visible is not a function
```

---
This is related to #327, the method indeed exists but is called `visible()` and not `isVisible()`.

**Comment by 38elements** [comment]
#425 will resolve this.

**Comment by eddyerburgh** [comment]
This is fixed in beta.12

**Comment by saintplay** [comment]
There is no [type](https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/types/index.d.ts) for `isVisible`

**Comment by eddyerburgh** [comment]
Are you able to make a PR?

**Comment by ntraykov** [comment]
Hey, guys! What is the status of this issue? Is it released? I have the same issue

**Comment by TheDeveloperTom** [comment]
I still have the problem. The last version.

Where is the "isVisible" method at all? 

Look at my wrapper prototype.

![image](https://user-images.githubusercontent.com/25426552/39355856-0a87d692-4a17-11e8-8a8f-5196f5db334b.png)

**Comment by eddyerburgh** [comment]
@TheDeveloperTom  Are you using `@vue/test-utils`?

The old `vue-test-utils` package is deprecated, and the latest version there is 11, which doesn't include `isVisible`

**Comment by TheDeveloperTom** [comment]
@eddyerburgh using what?

**Comment by TheDeveloperTom** [comment]
@eddyerburgh thank you

**Comment by gplusdotgr** [comment]
`      expect(wrapper.find('.panel').isVisible()).to.be(false);// isVisible
`

Object is not a constructor (evaluating 'expect(wrapper.find('.panel').isVisible()).to.be(false)')
